module OursprivacyIngest
  module Internal
    module Type
      type request_parameters =
        { request_options: OursprivacyIngest::request_opts }

      module RequestParameters
        attr_reader request_options: OursprivacyIngest::request_opts

        def request_options=: (
          OursprivacyIngest::request_opts
        ) -> OursprivacyIngest::request_opts

        module Converter
          def dump_request: (top params) -> [top, ::Hash[Symbol, top]]
        end
      end
    end
  end
end
