module OursprivacyIngest
  module Models
    type batch_create_response =
      {
        accepted: Integer,
        failed: Integer,
        results: ::Array[OursprivacyIngest::Models::BatchCreateResponse::result],
        success: bool
      }

    class BatchCreateResponse < OursprivacyIngest::Internal::Type::BaseModel
      attr_accessor accepted: Integer

      attr_accessor failed: Integer

      attr_accessor results: ::Array[OursprivacyIngest::Models::BatchCreateResponse::result]

      attr_accessor success: bool

      def initialize: (
        accepted: Integer,
        failed: Integer,
        results: ::Array[OursprivacyIngest::Models::BatchCreateResponse::result],
        success: bool
      ) -> void

      def to_hash: -> {
        accepted: Integer,
        failed: Integer,
        results: ::Array[OursprivacyIngest::Models::BatchCreateResponse::result],
        success: bool
      }

      type result =
        OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0
        | OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1

      module Result
        extend OursprivacyIngest::Internal::Type::Union

        type union_member0 =
          {
            index: Integer,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0::success
          }

        class UnionMember0 < OursprivacyIngest::Internal::Type::BaseModel
          attr_accessor index: Integer

          attr_accessor success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0::success

          def initialize: (
            index: Integer,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0::success
          ) -> void

          def to_hash: -> {
            index: Integer,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0::success
          }

          type success = true

          module Success
            extend OursprivacyIngest::Internal::Type::Enum

            TRUE: true

            def self?.values: -> ::Array[OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember0::success]
          end
        end

        type union_member1 =
          {
            code: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::code,
            index: Integer,
            message: String,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::success
          }

        class UnionMember1 < OursprivacyIngest::Internal::Type::BaseModel
          attr_accessor code: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::code

          attr_accessor index: Integer

          attr_accessor message: String

          attr_accessor success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::success

          def initialize: (
            code: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::code,
            index: Integer,
            message: String,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::success
          ) -> void

          def to_hash: -> {
            code: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::code,
            index: Integer,
            message: String,
            success: OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::success
          }

          type code = :invalid_event | :queue_failed

          module Code
            extend OursprivacyIngest::Internal::Type::Enum

            INVALID_EVENT: :invalid_event
            QUEUE_FAILED: :queue_failed

            def self?.values: -> ::Array[OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::code]
          end

          type success = false

          module Success
            extend OursprivacyIngest::Internal::Type::Enum

            FALSE: false

            def self?.values: -> ::Array[OursprivacyIngest::Models::BatchCreateResponse::Result::UnionMember1::success]
          end
        end

        def self?.variants: -> ::Array[OursprivacyIngest::Models::BatchCreateResponse::result]
      end
    end
  end
end
