module OursPrivacy
  module Resources
    class Track
      def event: (
        token: String,
        event: String,
        ?default_properties: OursPrivacy::TrackEventParams::DefaultProperties?,
        ?distinct_id: String?,
        ?email: String?,
        ?event_properties: ::Hash[Symbol, top?]?,
        ?external_id: String?,
        ?time: Float?,
        ?user_id: String?,
        ?user_properties: OursPrivacy::TrackEventParams::UserProperties?,
        ?request_options: OursPrivacy::request_opts
      ) -> OursPrivacy::Models::TrackEventResponse

      def initialize: (client: OursPrivacy::Client) -> void
    end
  end
end
