module OursPrivacy
  module Models
    type track_event_response =
      { success: OursPrivacy::Models::TrackEventResponse::success }

    class TrackEventResponse < OursPrivacy::Internal::Type::BaseModel
      attr_accessor success: OursPrivacy::Models::TrackEventResponse::success

      def initialize: (
        success: OursPrivacy::Models::TrackEventResponse::success
      ) -> void

      def to_hash: -> {
        success: OursPrivacy::Models::TrackEventResponse::success
      }

      type success = true

      module Success
        extend OursPrivacy::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[OursPrivacy::Models::TrackEventResponse::success]
      end
    end
  end
end
